version: "3.8"

services:
  web:
    build: ./web
    command: pnpm run dev  # Run the development server (Not production friendly)
    volumes:
      - ./web/src:/app/src
      - ./web/public:/app/public
    ports:
      - "3000:3000"
    depends_on:
      - api
    environment:
      NEXT_PUBLIC_API_BASE_URL: http://localhost:8000
  api:
    build: ./api
    command: sh -c 'python manage.py migrate && python manage.py runserver 0.0.0.0:8000' # Run the development server (Not production friendly)
    volumes:
      - ./api:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_NAME: mydatabase
      DATABASE_USER: myuser
      DATABASE_PASSWORD: mypassword
      DATABASE_HOST: db
      DATABASE_PORT: 5432
  db:
    image: postgres:15.0
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    volumes:
      - data:/var/lib/postgresql/data/
    ports:  
      - "5432:5432"

volumes:
  data: