version: "3"

services:
  web:
    build: ./web
    command: pnpm run dev  # Run the development server (Not production friendly)
    volumes:
      - ./web:/app
    ports:
      - "3000:3000"
    depends_on:
      - api
  api:
    build: ./api
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./api:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_NAME=mydatabase
      - DATABASE_USER=myuser
      - DATABASE_PASSWORD=myuser
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    volumes:
      - data:/var/lib/postgresql/data/

volumes:
  data: