FROM python:3.8

# Install pipenv
RUN pip install pipenv

# Copy everything into working directory
COPY . /app/

# Install Python dependencies
WORKDIR /app/
RUN pipenv install --ignore-pipfile --system

# Used by production only
RUN pipenv install gunicorn


